<Project>
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>0.2.2</Version>
    <Authors>Teirdalin</Authors>
    <Copyright>Copyright (c) 2026 Teirdalin. All rights reserved.</Copyright>
    <GameDir Condition="'$(GameDir)' == ''">D:\SteamLibrary\steamapps\common\SpaceEngineers2\Game2</GameDir>
  </PropertyGroup>
</Project>
